# Generated by Django 5.2.5 on 2025-08-15 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(choices=[('single_choice', 'Single Choice'), ('multi_select', 'Multi Select'), ('rating', 'Rating'), ('number', 'Number'), ('text', 'Text')], max_length=20)),
                ('question_text', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('scale', models.CharField(blank=True, max_length=20, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('instructions', models.TextField()),
                ('version', models.CharField(max_length=20)),
                ('created', models.DateField()),
                ('language', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_id', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(max_length=200)),
                ('text', models.CharField(blank=True, max_length=200, null=True)),
                ('is_other', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='eeusurvey_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='eeusurvey_app.survey')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eeusurvey_app.survey'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('survey', 'question_id')},
        ),
    ]
