version: '3.9'

services:
  # nodeapp:
  #   build: .
  #   container_name: my_node_app
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #     - DATABASE_URL=postgres://tyty:zxcvbnmm@db:5432/lenslocked
  #   depends_on:
  #     - db
  #   restart: always

  db:
    image: postgres:latest
    container_name: eeupg
    environment:
      POSTGRES_USER: eeu
      POSTGRES_PASSWORD: eeuzxcvbnm
      POSTGRES_DB: eeusurvey
    ports:
      - "5445:5432"
    volumes:
      - pgdata2:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata2:
